<style type="text/css">
    html, body { height: 100%; margin: 0; padding: 0; }
    #map { width: 400px; height: 400px; }
</style>
<?php $apiKey = $this->getApiKey() ?>
<div id="map"></div>
<script type="text/javascript">

    var map;
    function initMap() {
        var uluru = {lat: -25.363, lng: 131.044};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }

</script>
<script

        async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdMULs4rLjlVcQOgRCPPGxBGV62hH-SPo&callback=initMap">
</script>